// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth_center/v1/user/user.proto

package user

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=traceId,proto3" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordReply) Reset() {
	*x = UpdatePasswordReply{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReply) ProtoMessage() {}

func (x *UpdatePasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReply.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePasswordReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdatePasswordReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePasswordReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type DeleteAccountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=traceId,proto3" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountReply) Reset() {
	*x = DeleteAccountReply{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountReply) ProtoMessage() {}

func (x *DeleteAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountReply.ProtoReflect.Descriptor instead.
func (*DeleteAccountReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAccountReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteAccountReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteAccountReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetProfileReply struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Code          int32                                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetProfileReply_GetProfileReplyData `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	TraceId       string                               `protobuf:"bytes,4,opt,name=traceId,proto3" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReply) Reset() {
	*x = GetProfileReply{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReply) ProtoMessage() {}

func (x *GetProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReply.ProtoReflect.Descriptor instead.
func (*GetProfileReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetProfileReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetProfileReply) GetData() *GetProfileReply_GetProfileReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetProfileReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// string nick = 1;
// string realName = 2;
// string studentNumber = 3;
// string avatarUrl = 4;
// string gender = 5;
// string whutEmail = 6;
// string region = 7; // 校区
// string school = 8; // 院系
// string birthday = 9;
// string qq = 10;
// string phone = 11;
type UpdateProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=traceId,proto3" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReply) Reset() {
	*x = UpdateProfileReply{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReply) ProtoMessage() {}

func (x *UpdateProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReply.ProtoReflect.Descriptor instead.
func (*UpdateProfileReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateProfileReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateProfileReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetProfileKeysReply struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Code          int32                                        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetProfileKeysReply_GetProfileKeysReplyData `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	TraceId       string                                       `protobuf:"bytes,4,opt,name=traceId,proto3" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileKeysReply) Reset() {
	*x = GetProfileKeysReply{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileKeysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileKeysReply) ProtoMessage() {}

func (x *GetProfileKeysReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileKeysReply.ProtoReflect.Descriptor instead.
func (*GetProfileKeysReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileKeysReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetProfileKeysReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetProfileKeysReply) GetData() *GetProfileKeysReply_GetProfileKeysReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetProfileKeysReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type UpdateUserConsentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientVersion  string                 `protobuf:"bytes,2,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	OptionalScopes []string               `protobuf:"bytes,3,rep,name=optionalScopes,proto3" json:"optionalScopes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserConsentRequest) Reset() {
	*x = UpdateUserConsentRequest{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserConsentRequest) ProtoMessage() {}

func (x *UpdateUserConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserConsentRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserConsentRequest) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserConsentRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateUserConsentRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *UpdateUserConsentRequest) GetOptionalScopes() []string {
	if x != nil {
		return x.OptionalScopes
	}
	return nil
}

type UpdateUserConsentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=traceId,proto3" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserConsentReply) Reset() {
	*x = UpdateUserConsentReply{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserConsentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserConsentReply) ProtoMessage() {}

func (x *UpdateUserConsentReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserConsentReply.ProtoReflect.Descriptor instead.
func (*UpdateUserConsentReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserConsentReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateUserConsentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateUserConsentReply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetProfileReply_GetProfileReplyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReply_GetProfileReplyData) Reset() {
	*x = GetProfileReply_GetProfileReplyData{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReply_GetProfileReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReply_GetProfileReplyData) ProtoMessage() {}

func (x *GetProfileReply_GetProfileReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReply_GetProfileReplyData.ProtoReflect.Descriptor instead.
func (*GetProfileReply_GetProfileReplyData) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetProfileReply_GetProfileReplyData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfileReply_GetProfileReplyData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileReply_GetProfileReplyData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetProfileReply_GetProfileReplyData) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetProfileReply_GetProfileReplyData) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type GetProfileKeysReply_GetProfileKeysReplyData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseKeys         []string               `protobuf:"bytes,1,rep,name=baseKeys,proto3" json:"baseKeys,omitempty"`
	ExtraProfileKeys []string               `protobuf:"bytes,2,rep,name=extraProfileKeys,proto3" json:"extraProfileKeys,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProfileKeysReply_GetProfileKeysReplyData) Reset() {
	*x = GetProfileKeysReply_GetProfileKeysReplyData{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileKeysReply_GetProfileKeysReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileKeysReply_GetProfileKeysReplyData) ProtoMessage() {}

func (x *GetProfileKeysReply_GetProfileKeysReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileKeysReply_GetProfileKeysReplyData.ProtoReflect.Descriptor instead.
func (*GetProfileKeysReply_GetProfileKeysReplyData) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetProfileKeysReply_GetProfileKeysReplyData) GetBaseKeys() []string {
	if x != nil {
		return x.BaseKeys
	}
	return nil
}

func (x *GetProfileKeysReply_GetProfileKeysReplyData) GetExtraProfileKeys() []string {
	if x != nil {
		return x.ExtraProfileKeys
	}
	return nil
}

var File_auth_center_v1_user_user_proto protoreflect.FileDescriptor

const file_auth_center_v1_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1eauth_center/v1/user/user.proto\x12\x13auth_center.v1.user\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"[\n" +
	"\x15UpdatePasswordRequest\x12 \n" +
	"\voldPassword\x18\x01 \x01(\tR\voldPassword\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"]\n" +
	"\x13UpdatePasswordReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\atraceId\x18\x03 \x01(\tR\atraceId\"\\\n" +
	"\x12DeleteAccountReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\atraceId\x18\x03 \x01(\tR\atraceId\"\xcc\x03\n" +
	"\x0fGetProfileReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12Q\n" +
	"\x04data\x18\x03 \x01(\v28.auth_center.v1.user.GetProfileReply.GetProfileReplyDataH\x00R\x04data\x88\x01\x01\x12\x18\n" +
	"\atraceId\x18\x04 \x01(\tR\atraceId\x1a\x94\x02\n" +
	"\x13GetProfileReplyData\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\x03R\tupdatedAt\x12Y\n" +
	"\x05attrs\x18\x05 \x03(\v2C.auth_center.v1.user.GetProfileReply.GetProfileReplyData.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_data\"\\\n" +
	"\x12UpdateProfileReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\atraceId\x18\x03 \x01(\tR\atraceId\"\xa4\x02\n" +
	"\x13GetProfileKeysReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12Y\n" +
	"\x04data\x18\x03 \x01(\v2@.auth_center.v1.user.GetProfileKeysReply.GetProfileKeysReplyDataH\x00R\x04data\x88\x01\x01\x12\x18\n" +
	"\atraceId\x18\x04 \x01(\tR\atraceId\x1aa\n" +
	"\x17GetProfileKeysReplyData\x12\x1a\n" +
	"\bbaseKeys\x18\x01 \x03(\tR\bbaseKeys\x12*\n" +
	"\x10extraProfileKeys\x18\x02 \x03(\tR\x10extraProfileKeysB\a\n" +
	"\x05_data\"\x84\x01\n" +
	"\x18UpdateUserConsentRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12$\n" +
	"\rclientVersion\x18\x02 \x01(\tR\rclientVersion\x12&\n" +
	"\x0eoptionalScopes\x18\x03 \x03(\tR\x0eoptionalScopes\"`\n" +
	"\x16UpdateUserConsentReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\atraceId\x18\x03 \x01(\tR\atraceId2\xdb\x05\n" +
	"\x04User\x12\x88\x01\n" +
	"\x0eupdatePassword\x12*.auth_center.v1.user.UpdatePasswordRequest\x1a(.auth_center.v1.user.UpdatePasswordReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/user/update-password\x12n\n" +
	"\rdeleteAccount\x12\x16.google.protobuf.Empty\x1a'.auth_center.v1.user.DeleteAccountReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/user/delete-account\x12a\n" +
	"\n" +
	"getProfile\x12\x16.google.protobuf.Empty\x1a$.auth_center.v1.user.GetProfileReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/user/profile\x12r\n" +
	"\rupdateProfile\x12\x17.google.protobuf.Struct\x1a'.auth_center.v1.user.UpdateProfileReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/user/update-profile\x12n\n" +
	"\x0egetProfileKeys\x12\x16.google.protobuf.Empty\x1a(.auth_center.v1.user.GetProfileKeysReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/user/profile-keys\x12\x90\x01\n" +
	"\x11updateUserConsent\x12-.auth_center.v1.user.UpdateUserConsentRequest\x1a+.auth_center.v1.user.UpdateUserConsentReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/user/update-consentB/Z-iwut-auth_center/api/auth_center/v1/user;userb\x06proto3"

var (
	file_auth_center_v1_user_user_proto_rawDescOnce sync.Once
	file_auth_center_v1_user_user_proto_rawDescData []byte
)

func file_auth_center_v1_user_user_proto_rawDescGZIP() []byte {
	file_auth_center_v1_user_user_proto_rawDescOnce.Do(func() {
		file_auth_center_v1_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_center_v1_user_user_proto_rawDesc), len(file_auth_center_v1_user_user_proto_rawDesc)))
	})
	return file_auth_center_v1_user_user_proto_rawDescData
}

var file_auth_center_v1_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_auth_center_v1_user_user_proto_goTypes = []any{
	(*UpdatePasswordRequest)(nil),               // 0: auth_center.v1.user.UpdatePasswordRequest
	(*UpdatePasswordReply)(nil),                 // 1: auth_center.v1.user.UpdatePasswordReply
	(*DeleteAccountReply)(nil),                  // 2: auth_center.v1.user.DeleteAccountReply
	(*GetProfileReply)(nil),                     // 3: auth_center.v1.user.GetProfileReply
	(*UpdateProfileReply)(nil),                  // 4: auth_center.v1.user.UpdateProfileReply
	(*GetProfileKeysReply)(nil),                 // 5: auth_center.v1.user.GetProfileKeysReply
	(*UpdateUserConsentRequest)(nil),            // 6: auth_center.v1.user.UpdateUserConsentRequest
	(*UpdateUserConsentReply)(nil),              // 7: auth_center.v1.user.UpdateUserConsentReply
	(*GetProfileReply_GetProfileReplyData)(nil), // 8: auth_center.v1.user.GetProfileReply.GetProfileReplyData
	nil, // 9: auth_center.v1.user.GetProfileReply.GetProfileReplyData.AttrsEntry
	(*GetProfileKeysReply_GetProfileKeysReplyData)(nil), // 10: auth_center.v1.user.GetProfileKeysReply.GetProfileKeysReplyData
	(*emptypb.Empty)(nil),                               // 11: google.protobuf.Empty
	(*structpb.Struct)(nil),                             // 12: google.protobuf.Struct
}
var file_auth_center_v1_user_user_proto_depIdxs = []int32{
	8,  // 0: auth_center.v1.user.GetProfileReply.data:type_name -> auth_center.v1.user.GetProfileReply.GetProfileReplyData
	10, // 1: auth_center.v1.user.GetProfileKeysReply.data:type_name -> auth_center.v1.user.GetProfileKeysReply.GetProfileKeysReplyData
	9,  // 2: auth_center.v1.user.GetProfileReply.GetProfileReplyData.attrs:type_name -> auth_center.v1.user.GetProfileReply.GetProfileReplyData.AttrsEntry
	0,  // 3: auth_center.v1.user.User.updatePassword:input_type -> auth_center.v1.user.UpdatePasswordRequest
	11, // 4: auth_center.v1.user.User.deleteAccount:input_type -> google.protobuf.Empty
	11, // 5: auth_center.v1.user.User.getProfile:input_type -> google.protobuf.Empty
	12, // 6: auth_center.v1.user.User.updateProfile:input_type -> google.protobuf.Struct
	11, // 7: auth_center.v1.user.User.getProfileKeys:input_type -> google.protobuf.Empty
	6,  // 8: auth_center.v1.user.User.updateUserConsent:input_type -> auth_center.v1.user.UpdateUserConsentRequest
	1,  // 9: auth_center.v1.user.User.updatePassword:output_type -> auth_center.v1.user.UpdatePasswordReply
	2,  // 10: auth_center.v1.user.User.deleteAccount:output_type -> auth_center.v1.user.DeleteAccountReply
	3,  // 11: auth_center.v1.user.User.getProfile:output_type -> auth_center.v1.user.GetProfileReply
	4,  // 12: auth_center.v1.user.User.updateProfile:output_type -> auth_center.v1.user.UpdateProfileReply
	5,  // 13: auth_center.v1.user.User.getProfileKeys:output_type -> auth_center.v1.user.GetProfileKeysReply
	7,  // 14: auth_center.v1.user.User.updateUserConsent:output_type -> auth_center.v1.user.UpdateUserConsentReply
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_auth_center_v1_user_user_proto_init() }
func file_auth_center_v1_user_user_proto_init() {
	if File_auth_center_v1_user_user_proto != nil {
		return
	}
	file_auth_center_v1_user_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_auth_center_v1_user_user_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_center_v1_user_user_proto_rawDesc), len(file_auth_center_v1_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_center_v1_user_user_proto_goTypes,
		DependencyIndexes: file_auth_center_v1_user_user_proto_depIdxs,
		MessageInfos:      file_auth_center_v1_user_user_proto_msgTypes,
	}.Build()
	File_auth_center_v1_user_user_proto = out.File
	file_auth_center_v1_user_user_proto_goTypes = nil
	file_auth_center_v1_user_user_proto_depIdxs = nil
}
