// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth_center/v1/user/user.proto

package user

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       *string                `protobuf:"bytes,3,opt,name=traceId,proto3,oneof" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordReply) Reset() {
	*x = UpdatePasswordReply{}
	mi := &file_auth_center_v1_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReply) ProtoMessage() {}

func (x *UpdatePasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReply.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePasswordReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdatePasswordReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePasswordReply) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

var File_auth_center_v1_user_user_proto protoreflect.FileDescriptor

const file_auth_center_v1_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1eauth_center/v1/user/user.proto\x12\x13auth_center.v1.user\x1a\x1cgoogle/api/annotations.proto\"[\n" +
	"\x15UpdatePasswordRequest\x12 \n" +
	"\voldPassword\x18\x01 \x01(\tR\voldPassword\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"n\n" +
	"\x13UpdatePasswordReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\atraceId\x18\x03 \x01(\tH\x00R\atraceId\x88\x01\x01B\n" +
	"\n" +
	"\b_traceId2\x91\x01\n" +
	"\x04User\x12\x88\x01\n" +
	"\x0eupdatePassword\x12*.auth_center.v1.user.UpdatePasswordRequest\x1a(.auth_center.v1.user.UpdatePasswordReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/user/update-passwordB/Z-iwut-auth_center/api/auth_center/v1/user;userb\x06proto3"

var (
	file_auth_center_v1_user_user_proto_rawDescOnce sync.Once
	file_auth_center_v1_user_user_proto_rawDescData []byte
)

func file_auth_center_v1_user_user_proto_rawDescGZIP() []byte {
	file_auth_center_v1_user_user_proto_rawDescOnce.Do(func() {
		file_auth_center_v1_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_center_v1_user_user_proto_rawDesc), len(file_auth_center_v1_user_user_proto_rawDesc)))
	})
	return file_auth_center_v1_user_user_proto_rawDescData
}

var file_auth_center_v1_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_center_v1_user_user_proto_goTypes = []any{
	(*UpdatePasswordRequest)(nil), // 0: auth_center.v1.user.UpdatePasswordRequest
	(*UpdatePasswordReply)(nil),   // 1: auth_center.v1.user.UpdatePasswordReply
}
var file_auth_center_v1_user_user_proto_depIdxs = []int32{
	0, // 0: auth_center.v1.user.User.updatePassword:input_type -> auth_center.v1.user.UpdatePasswordRequest
	1, // 1: auth_center.v1.user.User.updatePassword:output_type -> auth_center.v1.user.UpdatePasswordReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_center_v1_user_user_proto_init() }
func file_auth_center_v1_user_user_proto_init() {
	if File_auth_center_v1_user_user_proto != nil {
		return
	}
	file_auth_center_v1_user_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_center_v1_user_user_proto_rawDesc), len(file_auth_center_v1_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_center_v1_user_user_proto_goTypes,
		DependencyIndexes: file_auth_center_v1_user_user_proto_depIdxs,
		MessageInfos:      file_auth_center_v1_user_user_proto_msgTypes,
	}.Build()
	File_auth_center_v1_user_user_proto = out.File
	file_auth_center_v1_user_user_proto_goTypes = nil
	file_auth_center_v1_user_user_proto_depIdxs = nil
}
