// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth_center/v1/auth/auth.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_USER_NOT_FOUND ErrorReason = 0
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "USER_NOT_FOUND",
	}
	ErrorReason_value = map[string]int32{
		"USER_NOT_FOUND": 0,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_center_v1_auth_auth_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_auth_center_v1_auth_auth_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_auth_center_v1_auth_auth_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          int32                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LoginReply_LoginReplyData `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginReply) GetData() *LoginReply_LoginReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetVerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeRequest) Reset() {
	*x = GetVerifyCodeRequest{}
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeRequest) ProtoMessage() {}

func (x *GetVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GetVerifyCodeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetVerifyCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetVerifyCodeReply struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Code          int32                                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetVerifyCodeReply_GetVerifyCodeReplyData `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeReply) Reset() {
	*x = GetVerifyCodeReply{}
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeReply) ProtoMessage() {}

func (x *GetVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetVerifyCodeReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVerifyCodeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVerifyCodeReply) GetData() *GetVerifyCodeReply_GetVerifyCodeReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_auth_auth_proto_rawDescGZIP(), []int{4}
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_auth_auth_proto_rawDescGZIP(), []int{5}
}

type LoginReply_LoginReplyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply_LoginReplyData) Reset() {
	*x = LoginReply_LoginReplyData{}
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply_LoginReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply_LoginReplyData) ProtoMessage() {}

func (x *LoginReply_LoginReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply_LoginReplyData.ProtoReflect.Descriptor instead.
func (*LoginReply_LoginReplyData) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_auth_auth_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LoginReply_LoginReplyData) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply_LoginReplyData) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetVerifyCodeReply_GetVerifyCodeReplyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeReply_GetVerifyCodeReplyData) Reset() {
	*x = GetVerifyCodeReply_GetVerifyCodeReplyData{}
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeReply_GetVerifyCodeReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeReply_GetVerifyCodeReplyData) ProtoMessage() {}

func (x *GetVerifyCodeReply_GetVerifyCodeReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeReply_GetVerifyCodeReplyData.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeReply_GetVerifyCodeReplyData) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_auth_auth_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetVerifyCodeReply_GetVerifyCodeReplyData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetVerifyCodeReply_GetVerifyCodeReplyData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_auth_center_v1_auth_auth_proto protoreflect.FileDescriptor

const file_auth_center_v1_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x1eauth_center/v1/auth/auth.proto\x12\x13auth_center.v1.auth\x1a\x1cgoogle/api/annotations.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xe4\x01\n" +
	"\n" +
	"LoginReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\x04data\x18\x03 \x01(\v2..auth_center.v1.auth.LoginReply.LoginReplyDataH\x00R\x04data\x88\x01\x01\x1aV\n" +
	"\x0eLoginReplyData\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshTokenB\a\n" +
	"\x05_data\"H\n" +
	"\x14GetVerifyCodeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\xf2\x01\n" +
	"\x12GetVerifyCodeReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12W\n" +
	"\x04data\x18\x03 \x01(\v2>.auth_center.v1.auth.GetVerifyCodeReply.GetVerifyCodeReplyDataH\x00R\x04data\x88\x01\x01\x1aL\n" +
	"\x16GetVerifyCodeReplyData\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busernameB\a\n" +
	"\x05_data\"\x11\n" +
	"\x0fRegisterRequest\"\x0f\n" +
	"\rRegisterReply*!\n" +
	"\vErrorReason\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x002\xed\x02\n" +
	"\x04Auth\x12k\n" +
	"\rpasswordLogin\x12!.auth_center.v1.auth.LoginRequest\x1a\x1f.auth_center.v1.auth.LoginReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/auth/login\x12\x86\x01\n" +
	"\x0fgetRegisterMail\x12).auth_center.v1.auth.GetVerifyCodeRequest\x1a'.auth_center.v1.auth.GetVerifyCodeReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/auth/get-register-mail\x12o\n" +
	"\bregister\x12$.auth_center.v1.auth.RegisterRequest\x1a\".auth_center.v1.auth.RegisterReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/auth/registerB/Z-iwut-auth_center/api/auth_center/v1/auth;authb\x06proto3"

var (
	file_auth_center_v1_auth_auth_proto_rawDescOnce sync.Once
	file_auth_center_v1_auth_auth_proto_rawDescData []byte
)

func file_auth_center_v1_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_center_v1_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_center_v1_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_center_v1_auth_auth_proto_rawDesc), len(file_auth_center_v1_auth_auth_proto_rawDesc)))
	})
	return file_auth_center_v1_auth_auth_proto_rawDescData
}

var file_auth_center_v1_auth_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_center_v1_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_center_v1_auth_auth_proto_goTypes = []any{
	(ErrorReason)(0),                                  // 0: auth_center.v1.auth.ErrorReason
	(*LoginRequest)(nil),                              // 1: auth_center.v1.auth.LoginRequest
	(*LoginReply)(nil),                                // 2: auth_center.v1.auth.LoginReply
	(*GetVerifyCodeRequest)(nil),                      // 3: auth_center.v1.auth.GetVerifyCodeRequest
	(*GetVerifyCodeReply)(nil),                        // 4: auth_center.v1.auth.GetVerifyCodeReply
	(*RegisterRequest)(nil),                           // 5: auth_center.v1.auth.RegisterRequest
	(*RegisterReply)(nil),                             // 6: auth_center.v1.auth.RegisterReply
	(*LoginReply_LoginReplyData)(nil),                 // 7: auth_center.v1.auth.LoginReply.LoginReplyData
	(*GetVerifyCodeReply_GetVerifyCodeReplyData)(nil), // 8: auth_center.v1.auth.GetVerifyCodeReply.GetVerifyCodeReplyData
}
var file_auth_center_v1_auth_auth_proto_depIdxs = []int32{
	7, // 0: auth_center.v1.auth.LoginReply.data:type_name -> auth_center.v1.auth.LoginReply.LoginReplyData
	8, // 1: auth_center.v1.auth.GetVerifyCodeReply.data:type_name -> auth_center.v1.auth.GetVerifyCodeReply.GetVerifyCodeReplyData
	1, // 2: auth_center.v1.auth.Auth.passwordLogin:input_type -> auth_center.v1.auth.LoginRequest
	3, // 3: auth_center.v1.auth.Auth.getRegisterMail:input_type -> auth_center.v1.auth.GetVerifyCodeRequest
	5, // 4: auth_center.v1.auth.Auth.register:input_type -> auth_center.v1.auth.RegisterRequest
	2, // 5: auth_center.v1.auth.Auth.passwordLogin:output_type -> auth_center.v1.auth.LoginReply
	4, // 6: auth_center.v1.auth.Auth.getRegisterMail:output_type -> auth_center.v1.auth.GetVerifyCodeReply
	6, // 7: auth_center.v1.auth.Auth.register:output_type -> auth_center.v1.auth.RegisterReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_center_v1_auth_auth_proto_init() }
func file_auth_center_v1_auth_auth_proto_init() {
	if File_auth_center_v1_auth_auth_proto != nil {
		return
	}
	file_auth_center_v1_auth_auth_proto_msgTypes[1].OneofWrappers = []any{}
	file_auth_center_v1_auth_auth_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_center_v1_auth_auth_proto_rawDesc), len(file_auth_center_v1_auth_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_center_v1_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_center_v1_auth_auth_proto_depIdxs,
		EnumInfos:         file_auth_center_v1_auth_auth_proto_enumTypes,
		MessageInfos:      file_auth_center_v1_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_center_v1_auth_auth_proto = out.File
	file_auth_center_v1_auth_auth_proto_goTypes = nil
	file_auth_center_v1_auth_auth_proto_depIdxs = nil
}
