// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth_center/v1/v1.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       *string                `protobuf:"bytes,3,opt,name=traceId,proto3,oneof" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonReply) Reset() {
	*x = CommonReply{}
	mi := &file_auth_center_v1_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReply) ProtoMessage() {}

func (x *CommonReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReply.ProtoReflect.Descriptor instead.
func (*CommonReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_v1_proto_rawDescGZIP(), []int{0}
}

func (x *CommonReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonReply) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

var File_auth_center_v1_v1_proto protoreflect.FileDescriptor

const file_auth_center_v1_v1_proto_rawDesc = "" +
	"\n" +
	"\x17auth_center/v1/v1.proto\x12\x0eauth_center.v1\x1a\x1cgoogle/api/annotations.proto\"f\n" +
	"\vCommonReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\atraceId\x18\x03 \x01(\tH\x00R\atraceId\x88\x01\x01B\n" +
	"\n" +
	"\b_traceIdB(Z&iwut-auth_center/api/auth_center/v1;v1b\x06proto3"

var (
	file_auth_center_v1_v1_proto_rawDescOnce sync.Once
	file_auth_center_v1_v1_proto_rawDescData []byte
)

func file_auth_center_v1_v1_proto_rawDescGZIP() []byte {
	file_auth_center_v1_v1_proto_rawDescOnce.Do(func() {
		file_auth_center_v1_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_center_v1_v1_proto_rawDesc), len(file_auth_center_v1_v1_proto_rawDesc)))
	})
	return file_auth_center_v1_v1_proto_rawDescData
}

var file_auth_center_v1_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_center_v1_v1_proto_goTypes = []any{
	(*CommonReply)(nil), // 0: auth_center.v1.CommonReply
}
var file_auth_center_v1_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_center_v1_v1_proto_init() }
func file_auth_center_v1_v1_proto_init() {
	if File_auth_center_v1_v1_proto != nil {
		return
	}
	file_auth_center_v1_v1_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_center_v1_v1_proto_rawDesc), len(file_auth_center_v1_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_center_v1_v1_proto_goTypes,
		DependencyIndexes: file_auth_center_v1_v1_proto_depIdxs,
		MessageInfos:      file_auth_center_v1_v1_proto_msgTypes,
	}.Build()
	File_auth_center_v1_v1_proto = out.File
	file_auth_center_v1_v1_proto_goTypes = nil
	file_auth_center_v1_v1_proto_depIdxs = nil
}
