// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: auth_center/v1/oauth2/oauth2.proto

package oauth2

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOAuth2authorize = "/auth_center.v1.oauth2.OAuth2/authorize"

type OAuth2HTTPServer interface {
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeReply, error)
}

func RegisterOAuth2HTTPServer(s *http.Server, srv OAuth2HTTPServer) {
	r := s.Route("/")
	r.GET("/oauth2/authorize", _OAuth2_Authorize0_HTTP_Handler(srv))
}

func _OAuth2_Authorize0_HTTP_Handler(srv OAuth2HTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuthorizeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOAuth2authorize)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Authorize(ctx, req.(*AuthorizeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuthorizeReply)
		return ctx.Result(200, reply)
	}
}

type OAuth2HTTPClient interface {
	Authorize(ctx context.Context, req *AuthorizeRequest, opts ...http.CallOption) (rsp *AuthorizeReply, err error)
}

type OAuth2HTTPClientImpl struct {
	cc *http.Client
}

func NewOAuth2HTTPClient(client *http.Client) OAuth2HTTPClient {
	return &OAuth2HTTPClientImpl{client}
}

func (c *OAuth2HTTPClientImpl) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...http.CallOption) (*AuthorizeReply, error) {
	var out AuthorizeReply
	pattern := "/oauth2/authorize"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOAuth2authorize))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
