// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth_center/v1/oauth2/oauth2.proto

package oauth2

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseType  string                 `protobuf:"bytes,1,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_auth_center_v1_oauth2_oauth2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_oauth2_oauth2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_oauth2_oauth2_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *AuthorizeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorizeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AuthorizeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AuthorizeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type AuthorizeReply struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Code          int32                              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AuthorizeReply_AuthorizeReplyData `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	TraceId       *string                            `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3,oneof" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeReply) Reset() {
	*x = AuthorizeReply{}
	mi := &file_auth_center_v1_oauth2_oauth2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeReply) ProtoMessage() {}

func (x *AuthorizeReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_oauth2_oauth2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeReply.ProtoReflect.Descriptor instead.
func (*AuthorizeReply) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_oauth2_oauth2_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthorizeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthorizeReply) GetData() *AuthorizeReply_AuthorizeReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuthorizeReply) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

type AuthorizeReply_AuthorizeReplyData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationCode string                 `protobuf:"bytes,1,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	RedirectUri       string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State             string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthorizeReply_AuthorizeReplyData) Reset() {
	*x = AuthorizeReply_AuthorizeReplyData{}
	mi := &file_auth_center_v1_oauth2_oauth2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeReply_AuthorizeReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeReply_AuthorizeReplyData) ProtoMessage() {}

func (x *AuthorizeReply_AuthorizeReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_center_v1_oauth2_oauth2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeReply_AuthorizeReplyData.ProtoReflect.Descriptor instead.
func (*AuthorizeReply_AuthorizeReplyData) Descriptor() ([]byte, []int) {
	return file_auth_center_v1_oauth2_oauth2_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AuthorizeReply_AuthorizeReplyData) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *AuthorizeReply_AuthorizeReplyData) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AuthorizeReply_AuthorizeReplyData) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_auth_center_v1_oauth2_oauth2_proto protoreflect.FileDescriptor

const file_auth_center_v1_oauth2_oauth2_proto_rawDesc = "" +
	"\n" +
	"\"auth_center/v1/oauth2/oauth2.proto\x12\x15auth_center.v1.oauth2\x1a\x1cgoogle/api/annotations.proto\"\xa3\x01\n" +
	"\x10AuthorizeRequest\x12#\n" +
	"\rresponse_type\x18\x01 \x01(\tR\fresponseType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\"\xc5\x02\n" +
	"\x0eAuthorizeReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12Q\n" +
	"\x04data\x18\x03 \x01(\v28.auth_center.v1.oauth2.AuthorizeReply.AuthorizeReplyDataH\x00R\x04data\x88\x01\x01\x12\x1e\n" +
	"\btrace_id\x18\x04 \x01(\tH\x01R\atraceId\x88\x01\x01\x1a|\n" +
	"\x12AuthorizeReplyData\x12-\n" +
	"\x12authorization_code\x18\x01 \x01(\tR\x11authorizationCode\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05stateB\a\n" +
	"\x05_dataB\v\n" +
	"\t_trace_id2\x80\x01\n" +
	"\x06OAuth2\x12v\n" +
	"\tauthorize\x12'.auth_center.v1.oauth2.AuthorizeRequest\x1a%.auth_center.v1.oauth2.AuthorizeReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/oauth2/authorizeB3Z1iwut-auth_center/api/auth_center/v1/oauth2;oauth2b\x06proto3"

var (
	file_auth_center_v1_oauth2_oauth2_proto_rawDescOnce sync.Once
	file_auth_center_v1_oauth2_oauth2_proto_rawDescData []byte
)

func file_auth_center_v1_oauth2_oauth2_proto_rawDescGZIP() []byte {
	file_auth_center_v1_oauth2_oauth2_proto_rawDescOnce.Do(func() {
		file_auth_center_v1_oauth2_oauth2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_center_v1_oauth2_oauth2_proto_rawDesc), len(file_auth_center_v1_oauth2_oauth2_proto_rawDesc)))
	})
	return file_auth_center_v1_oauth2_oauth2_proto_rawDescData
}

var file_auth_center_v1_oauth2_oauth2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_center_v1_oauth2_oauth2_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),                  // 0: auth_center.v1.oauth2.AuthorizeRequest
	(*AuthorizeReply)(nil),                    // 1: auth_center.v1.oauth2.AuthorizeReply
	(*AuthorizeReply_AuthorizeReplyData)(nil), // 2: auth_center.v1.oauth2.AuthorizeReply.AuthorizeReplyData
}
var file_auth_center_v1_oauth2_oauth2_proto_depIdxs = []int32{
	2, // 0: auth_center.v1.oauth2.AuthorizeReply.data:type_name -> auth_center.v1.oauth2.AuthorizeReply.AuthorizeReplyData
	0, // 1: auth_center.v1.oauth2.OAuth2.authorize:input_type -> auth_center.v1.oauth2.AuthorizeRequest
	1, // 2: auth_center.v1.oauth2.OAuth2.authorize:output_type -> auth_center.v1.oauth2.AuthorizeReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_center_v1_oauth2_oauth2_proto_init() }
func file_auth_center_v1_oauth2_oauth2_proto_init() {
	if File_auth_center_v1_oauth2_oauth2_proto != nil {
		return
	}
	file_auth_center_v1_oauth2_oauth2_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_center_v1_oauth2_oauth2_proto_rawDesc), len(file_auth_center_v1_oauth2_oauth2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_center_v1_oauth2_oauth2_proto_goTypes,
		DependencyIndexes: file_auth_center_v1_oauth2_oauth2_proto_depIdxs,
		MessageInfos:      file_auth_center_v1_oauth2_oauth2_proto_msgTypes,
	}.Build()
	File_auth_center_v1_oauth2_oauth2_proto = out.File
	file_auth_center_v1_oauth2_oauth2_proto_goTypes = nil
	file_auth_center_v1_oauth2_oauth2_proto_depIdxs = nil
}
