// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"iwut-auth-center/internal/biz"
	"iwut-auth-center/internal/biz/mail"
	"iwut-auth-center/internal/conf"
	"iwut-auth-center/internal/data"
	"iwut-auth-center/internal/middleware"
	"iwut-auth-center/internal/server"
	"iwut-auth-center/internal/service"
	"iwut-auth-center/internal/util"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.Jwt, confMail *conf.Mail, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	sha256Util := util.NewSha256Util(jwt)
	authRepo := data.NewAuthRepo(dataData, confData, logger, sha256Util)
	authUsecase := biz.NewAuthUsecase(authRepo)
	usecase := mail.NewMailUsecase(confMail, logger)
	auditRepo, cleanup2, err := data.NewAuditRepo(dataData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auditUsecase := biz.NewAuditUsecase(auditRepo)
	jwtUtil := util.NewJwtUtil(jwt)
	authService := service.NewAuthService(authUsecase, usecase, auditUsecase, jwtUtil, jwt)
	appRepo := data.NewAppRepo(dataData, logger)
	appUsecase := biz.NewAppUsecase(appRepo)
	userRepo := data.NewUserRepo(dataData, confData, logger, appUsecase, sha256Util)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService, err := service.NewUserService(userUsecase, authUsecase, auditUsecase, jwtUtil, jwt)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	oauth2Repo := data.NewOauth2Repo(dataData, confData, jwt, appUsecase, logger)
	oauth2Usecase := biz.NewOauth2Usecase(oauth2Repo)
	oauth2Service := service.NewOauth2Service(oauth2Usecase, auditUsecase, appUsecase, jwtUtil, jwt)
	jwtCheckMiddleware := middleware.NewJwtCheckMiddleware(authUsecase, oauth2Usecase, jwtUtil)
	grpcServer := server.NewGRPCServer(confServer, authService, userService, oauth2Service, jwtCheckMiddleware, logger)
	httpServer := server.NewHTTPServer(confServer, authService, userService, oauth2Service, jwtCheckMiddleware, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
