// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"iwut-auth-center/internal/biz"
	"iwut-auth-center/internal/biz/mail"
	"iwut-auth-center/internal/conf"
	"iwut-auth-center/internal/data"
	"iwut-auth-center/internal/middleware"
	"iwut-auth-center/internal/server"
	"iwut-auth-center/internal/service/auth"
	"iwut-auth-center/internal/service/user"
	"iwut-auth-center/internal/util"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.Jwt, confMail *conf.Mail, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	sha256Util := util.NewSha256Util(jwt)
	authRepo := data.NewAuthRepo(dataData, confData, logger, sha256Util)
	authUsecase := biz.NewAuthUsecase(authRepo)
	usecase := mail.NewMailUsecase(confMail, logger)
	jwtUtil := util.NewJwtUtil(jwt)
	service := auth.NewAuthService(authUsecase, usecase, jwtUtil, jwt)
	userRepo := data.NewUserRepo(dataData, confData, logger, sha256Util)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService, err := user.NewUserService(userUsecase, authUsecase, jwtUtil, jwt)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, service, userService)
	jwtCheckMiddleware := middleware.NewJwtCheckMiddleware(authUsecase, jwtUtil)
	httpServer := server.NewHTTPServer(confServer, service, userService, jwtCheckMiddleware)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
